import { ImportedConversationEvent } from '../types';
import { TimelineEvent } from '../../../job_scheduling/types';

/**
 * Maps an ImportedConversationEvent to a TimelineEvent.
 * Does NOT generate a final ID (should be generated by the caller or backend)
 * Does NOT upload attachments (should be handled by the caller before final mapping if zip is supported)
 */
export function mapImportedEventToTimelineEvent(
    event: ImportedConversationEvent, 
    currentUserUid: string,
    currentUserName: string
): Omit<TimelineEvent, 'id' | 'timestamp'> & { id?: string, timestamp: any } {
    
    // We treat imported WhatsApp messages as comments
    const tipo = 'comentario'; 
    
    return {
        tipo,
        mensaje: event.message,
        timestamp: event.timestamp, 
        createdAt: event.timestamp.toISOString(),
        createdAtMs: event.timestamp.getTime(),
        usuarioId: 'whatsapp_import', 
        usuarioNombre: event.author,
        isOptimistic: false,
        source: 'whatsapp',
        sourceMetadata: {
            platform: 'whatsapp',
            originalAuthor: event.author,
            originalTimestamp: event.timestamp,
            chatName: event.metadata?.chatName
        },
        fileUrls: [], // If we had real attachments uploaded, they'd go here
        fileNames: event.attachments.map(a => a.fileName),
        fileSizes: [] // We don't have sizes for just filenames
    };
}
